version: '3'

services:
  # Laravel application container
  api:
    build:
      context: ./api
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
  # mysql database container
  db:
    image: mysql
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app-network

  # Nuxt.js application container
  client:
    build:
      context: ./client
    depends_on:
      - api
    networks:
      - app-network

  # nginx container   
  nginx:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      # certificate and key are fake (self signed)
      - ./certs:/etc/nginx/certs
    depends_on:
      - client
    networks:
      - app-network

networks:
  app-network:
    driver: bridge