version: '3'

services:
  api:
    build:
      context: ./api
    depends_on:
      db:
        condition: service_healthy
    networks:
      app-network:
        ipv4_address: 172.20.0.2  # Static IP address for the api service

  db:
    image: mysql
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      app-network:
        ipv4_address: 172.20.0.3  # You can assign a static IP for the db service if needed

  client:
    build:
      context: ./client
    ports:
      - 3000:3000
    depends_on:
      - api
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - client
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16  # IP address range for the app-network

volumes:
  mysql_data:
